### ISSUE TITLE
Check if Celery worker server is running, and if not, eschew Celery and execute tasks in serial

### ISSUE THREAD

**Issue by acrellin** [mltsp/mltsp#102]
Users may want to `pip install mltsp` without installing and running RabbitMQ & Celery, & MLTSP should still be able to do everything serially.

**Comment by acrellin** [comment]
@bnaul @stefanv Did we decide last week that it's fine to just require people to install & run RabbitMQ/Celery for full MLTSP functionality? Should this issue be closed?

**Comment by bnaul** [comment]
Yep, I believe that's what we decided. Users can still call `featurize.featurize_time_series` without Celery installed which I think is good enough.
