### ISSUE TITLE
Keep uploaded TS datasets on disk & store file URI in database for future use

### ISSUE THREAD

**Issue by acrellin** [mltsp/mltsp#104]
Add checks such that a dataset cannot be delete if there are results that depend on that dataset, or at least warn the user about the consequences before proceeding.

**Comment by acrellin** [comment]
@bnaul, did your featurization refactor address this issue?

**Comment by bnaul** [comment]
No, it just changed in the other direction: now instead of datasets
disappearing instantly, they just stick around forever. We aren't storing
the paths in the database or anything.

**Comment by acrellin** [comment]
Ok, so the paths just need to be stored in the db now. I'll do a quick fix soon.

**Comment by bnaul** [comment]
Just realized I have 500MB of extracted time series hiding out various `tempfile` directories (`/var/folders/ts/...`). Figure this is the same issue, just thought I'd make a note that whatever we do for file handling should also remember to remove these temporarily directories.

**Comment by bnaul** [comment]
We do store the URI in the database now so I'm closing this; #99 contains other data handling improvements.
