### ISSUE TITLE
Use LombScargleFast from gatspy?

### ISSUE THREAD

**Issue by bnaul** [mltsp/mltsp#111]
I did a quick benchmark of our Lomb-Scargle implementation versus the ones in `gatspy`.
## Benchmark
```python
N = 2001
times = np.sort(np.random.random(size=N))
values = 8 * np.sin(2*np.pi*times*5.3 + 0.1) + np.random.normal(scale=0.1, size=N)  # sinusoidal-ish
errors = np.random.exponential(scale=0.1, size=N)

# Use parameters comparable to our LS implementation
opt_args = {'period_range': (1./33., times.max()), 'quiet': True}
# 8-harmonic model with regularization (our default)
%timeit gatspy.periodic.LombScargle(Nterms=8, regularization=1., regularize_by_trace=False, fit_period=True, optimizer_kwds=opt_args).fit(times, values, errors)
# 1-harmonic model without regularization (Fast version)
%timeit gatspy.periodic.LombScargleFast(fit_period=True, optimizer_kwds=opt_args).fit(times, values, errors)

# Use roughly the same number of grid points as gatspy chooses
numf = 1500
df = (33 - 1./times.max()) / numf
# 8-harmonic model with regularization (our default)
%timeit fit_lomb_scargle(times, values, errors, 1/times.max(), df, numf)
# 1-harmonic model without regularization (Fast version)
%timeit fit_lomb_scargle(times, values, errors, 1/times.max(), df, numf, lambda0=0., nharm=1)
```

## Output
```
1 loops, best of 3:     962 ms per loop        # gatspy, full model
100 loops, best of 3:    22 ms per loop        # gatspy, simple model
1 loops, best of 3:     888 ms per loop        # ours, full model
1 loops, best of 3:     239 ms per loop        # ours, simple model
```

## Conclusion
The `LombScargleFast` function from `gatspy`, which fits a much simpler model to the data, is much faster than our C implementation. I think it would be good to add some features based on `LombScargleFast`, since they would be faster and easier to understand for non-expert users. We could leave in the existing implementation as it computes some additional statistical quantities which the `gatspy` functions do not, but these seem like features that only really expert users would be interested in.

Thoughts?

**Comment by stefanv** [comment]
How hard would it be to update ``gatspy`` to calculate the same statistical quantities?  Or, can we build those on top of ``gatspy``?  How does the output of ``gatspy`` compare to ours?

**Comment by bnaul** [comment]
I think it's mostly doable. The major things not included in `gatspy` are:
- Support for multiple frequencies --> **easy to build on top**
- Automatic selection of regularization parameter --> **implementing this exactly the same way that ours works is probably not possible; however, achieving something functionally equivalent might be**
- Statistical significance of fit --> **easy to build on top**
- Estimate linear trend --> **would need to add to `gatspy` but this seems straightforward and like a sensible addition**

My preference would be to ditch our implementation altogether since I think it is literally unmaintainable (I have spent hours looking at the code and about 50% of it is still totally inscrutable) and adds an additional layer of complexity (compiling Cython code) to our stack with little benefit.

**Comment by acrellin** [comment]
I strongly vote for replacing the TCP implementation with `gatspy` if possible. If we don't understand it and can't maintain it, we shouldn't be using it.

**Comment by stefanv** [comment]
I agree. If we can contribute missing functionality back to gatspy and
build the rest on top, that'd be excellent.
