### ISSUE TITLE
Sample datasets module

### ISSUE THREAD

**Issue by bnaul** [mltsp/mltsp#114]
It would be nice to have a module (`mltsp.datasets`?) that allows for easy fetching of a few sample datasets; any tutorials we write up could then use these built-in functions rather than requiring the user to manually download the data.

1. Is it ok to download data from public URLs out of our control or should we host them ourselves?
2. `asas_training_set.tar.gz` in `mltsp/data/sample_data` isn't being used by any tests; we could migrate it out of the repo and instead make it downloadable through `mltsp.datasets`? EDIT: we could also just keep the relevant data in the repo, `asas_training_set.tar.gz` is ~3MB and my EEG dataset is ~6MB, dunno if that's too large or not.

**Comment by stefanv** [comment]
Downloading from public URLs is okay.  We should not implement ourselves---the functionality already exists in NiPy somewhere.  @matthew-brett, could you point us to the latest downloader code?  Otherwise, we can borrow scikit-learn's implementation.

**Comment by stefanv** [comment]
I'd vote for moving datasets out of the repo.

**Comment by bnaul** [comment]
@matthew-brett any idea if there's something relevant in NiPy we could use for downloading datasets? @stefanv scikit-learn just implements it in every file (see, e.g., (datasets.kddcup99)[https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/datasets/kddcup99.py]). I have no problem just copying their skeleton and adapting it but you seemed averse to that :grimacing:

**Comment by stefanv** [comment]
I was hoping that we'd have something better in place, preferably something that does md5 checking at least.  Let's sit down with Matthew as soon as he is back and see if we can come up with a minimal spec to implement (the neuro-packages would find this useful as well).

**Comment by bnaul** [comment]
`nilearn` does do md5 checking: https://github.com/nilearn/nilearn/tree/master/nilearn/datasets. We could consider adapting this for our purposes.

Personally I don't think it's worth us devoting a huge amount of time for this: right now we need to support downloading zip files containing a few MB of text, which seems like it should be pretty straightforward. The way `sklearn.datasets` does things is simple and fast and is going to work 99.9% of the time; whenever it doesn't, we can just make them re-download the raw data, which is quick and painless.

**Comment by stefanv** [comment]
From past experience, I know this will break, and in unpredictable ways.  Let's just make this robust enough to avoid 90% of bad breakages; it's a pain-saving measure.

**Comment by stefanv** [comment]
(I.e., as long as we do basic checksum checking and re-downloading for broken files, we should be fine.)

**Comment by bnaul** [comment]
Just to clarify: the flow as I copied from `sklearn` is:
- Download raw data
- Process text files into our preferred format
- Save a compressed version to disk (they're using `joblib` but I could use netCDF via `xray` instead; I know pickling is icky)

I also save a `.tar.gz` archive and a `.csv` header file, for use with either the front end or the relevant back-end functions.

So I assume the idea would be to checksum all three of these, and if anything doesn't match we just re-download and build the archives from scratch?

**Comment by stefanv** [comment]
Or just checksum the original download?  That might be a bit easier to
implement.  But either way sounds fine!

**Comment by bnaul** [comment]
:+1:
