### ISSUE TITLE
Make a Logo!

### ISSUE THREAD

**Issue by profjsb** [mltsp/mltsp#46]
![image](https://cloud.githubusercontent.com/assets/480799/8859332/7af1479e-3131-11e5-9f10-9ec25a320308.png)

**Comment by profjsb** [comment]
idea with this one is it's "machine learning, made easy, served on a silver (tea) spoon"

**Comment by stefanv** [comment]
I like that concept!

**Comment by profjsb** [comment]
so be it. done.
