### ISSUE TITLE
Check Web site: http://mltsp.io/

### ISSUE THREAD

**Issue by esafak** [mltsp/mltsp#48]
It's currently down, so it might be worth considering backups or more reliable third party hosting such as ReadTheDocs.

**Comment by stefanv** [comment]
Can you check again?  The website is hosted on GitHub, so it should be
very reliable.  The docs are already hosted on readthedocs.org.

**Comment by esafak** [comment]
... and it's back! I was getting an nginx error.

**Comment by stefanv** [comment]
The problem seems to be back.  I'll investigate further.

**Comment by stefanv** [comment]
Looks like a problem on the DNS provider side: I've notified them 
of the issue.

**Comment by profjsb** [comment]
fixed on DNS provider side.
