### ISSUE TITLE
Docker in OS X

### ISSUE THREAD

**Issue by bnaul** [mltsp/mltsp#55]
I was troubleshooting my Docker installation but it looks like everything is set up correctly and the issue is a bit more complicated: on OS X, Docker is actually running inside a Linux VM, so in particular there is no local `/var/run/docker.sock` file as is referenced in `util.py`.

Happy to look into this if you like, I could stand to get a bit more familiar with Docker...

**Comment by stefanv** [comment]
By default, DockerPy is able to automatically detect where to connect to.
If we can test on your machine, Brett, I think we should be able to fix
this one quickly.

**Comment by acrellin** [comment]
Did the last PR resolve this?

**Comment by stefanv** [comment]
Fixed in https://github.com/mltsp/mltsp/pull/57
