### ISSUE TITLE
Consider these features for inclusion

### ISSUE THREAD

**Issue by stefanv** [mltsp/mltsp#71]
From an e-mail Josh wrote earlier:

Table 4 and 5:
   http://iopscience.iop.org/0004-637X/733/1/10/pdf/apj_733_1_10.pdf <http://iopscience.iop.org/0004-637X/733/1/10/pdf/apj_733_1_10.pdf>

(with a few links to other papers for those, including Stetson indices)

a good extension can be found in papers referencing this one (http://adsabs.harvard.edu/cgi-bin/nph-ref_query?bibcode=2011ApJ...733...10R&amp;refs=CITATIONS&amp;db_key=AST <http://adsabs.harvard.edu/cgi-bin/nph-ref_query?bibcode=2011ApJ...733...10R&amp;refs=CITATIONS&amp;db_key=AST>). Eg. this paper looks interesting http://mnras.oxfordjournals.org/content/437/1/147.full.pdf <http://mnras.oxfordjournals.org/content/437/1/147.full.pdf>

**Comment by acrellin** [comment]
The features described in that paper are the TCP features that we're already using... am I missing something?

**Comment by stefanv** [comment]
I found this in an old email from Josh, so just wanted to double check.  Thanks.
