### ISSUE TITLE
Improve API for featurization/model building/prediction

### ISSUE THREAD

**Issue by bnaul** [mltsp/mltsp#88]
Right now everything is decomposed in a way that makes sense from the perspective of doing computation driven by requests from the front end. But trying to call our code directly to analyze a dataset is kind of a nightmare: the functions for featurization, model building, and prediction all operate on file paths where either data or some output from another task is stored. So any task that wants to make use of just part of our pipeline (without conforming entirely to our way of handling data) is basically impossible.

It would be much better if our back end was composed of more elementary functions that were usable in their own right (I don't know exactly what that would look like yet). Right now I'd say our API is useless for anything except an exact reproduction of a workflow from the front end.

**Comment by stefanv** [comment]
Brett, I think you should feel free to refactor mercilessly to improve this situation.

**Comment by acrellin** [comment]
Agreed!

**Comment by acrellin** [comment]
But wait for my next PR or you'll have an endless mess of conflicts...

**Comment by bnaul** [comment]
Sure thing...not planning to start right away, just making a note for the future.

**Comment by bnaul** [comment]
Fixed (at least the changes I had in mind) by #106.
